/*CREACIÓN DE TABLAS*/

CREATE TABLE AUTOR(
	NOMBRE VARCHAR(255) PRIMARY KEY, 
	NACIONALIDAD VARCHAR(255) NOT NULL,
	FECHANACIMIENTO DATE NOT NULL
);

CREATE TABLE RECURSO(
	CODIGO VARCHAR(13) PRIMARY KEY,
	TITULO VARCHAR(255) NOT NULL,
	EDITORIAL VARCHAR(255) NOT NULL,
	FECHAPUBLICACION DATE NOT NULL
);

CREATE TABLE RECURSOAUTOR(
	NOMBRE_AUTOR VARCHAR(255),
	CODIGO_RECURSO VARCHAR(13),
	FOREIGN KEY (CODIGO_RECURSO) REFERENCES RECURSO (CODIGO) ON DELETE CASCADE,
	FOREIGN KEY (NOMBRE_AUTOR) REFERENCES AUTOR (NOMBRE) ON DELETE CASCADE,
	PRIMARY KEY (NOMBRE_AUTOR, CODIGO_RECURSO)
);

CREATE TABLE GENEROLIBRO (	
	CODIGO INT PRIMARY KEY,
	GENERO VARCHAR(255) NOT NULL UNIQUE,
	CONSTRAINT GL1 CHECK (GENERO IN('INFANTIL', 'IDIOMAS', 'NOVELA', 'POESIA', 'TEATRO', 'ENSAYO', 'COMIC', 'JUVENIL', 'TECNICO'))
);

CREATE TABLE PERIODICIDADREVISTA (	
	CODIGO INT PRIMARY KEY,
	PERIODICIDAD VARCHAR(255) NOT NULL UNIQUE,
	CONSTRAINT PR1 CHECK (PERIODICIDAD IN ('SEMANAL', 'MENSUAL', 'ANUAL'))
);

CREATE TABLE LIBRO (	
	CODIGO_RECURSO VARCHAR(13),
	CODIGO_GENERO INT,
	FOREIGN KEY (CODIGO_RECURSO) REFERENCES RECURSO (CODIGO) ON DELETE CASCADE,
	FOREIGN KEY (CODIGO_GENERO) REFERENCES GENEROLIBRO (CODIGO),
	PRIMARY KEY (CODIGO_RECURSO)
);


CREATE TABLE REVISTA (	
	CODIGO_RECURSO VARCHAR(13),
	CODIGO_PERIODICIDAD INT,
	FOREIGN KEY (CODIGO_RECURSO) REFERENCES RECURSO (CODIGO) ON DELETE CASCADE,
	FOREIGN KEY (CODIGO_PERIODICIDAD) REFERENCES PERIODICIDADREVISTA (CODIGO),
	PRIMARY KEY (CODIGO_RECURSO)
);

