/* INSERTS DE GENEROLIBRO*/

INSERT INTO GENEROLIBRO VALUES(1, 'INFANTIL');
INSERT INTO GENEROLIBRO VALUES(2, 'IDIOMAS');
INSERT INTO GENEROLIBRO VALUES(3, 'NOVELA');
INSERT INTO GENEROLIBRO VALUES(4, 'TEATRO');
INSERT INTO GENEROLIBRO VALUES(5, 'POESIA');
INSERT INTO GENEROLIBRO VALUES(6, 'ENSAYO');
INSERT INTO GENEROLIBRO VALUES(7, 'COMIC');
INSERT INTO GENEROLIBRO VALUES(8, 'JUVENIL');
INSERT INTO GENEROLIBRO VALUES(9, 'TECNICO');

/* INSERTS DE PERIODICIDADREVISTA*/

INSERT INTO PERIODICIDADREVISTA VALUES(1, 'SEMANAL');
INSERT INTO PERIODICIDADREVISTA VALUES(2, 'MENSUAL');
INSERT INTO PERIODICIDADREVISTA VALUES(3, 'ANUAL');

